/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.AtributosClientes;
import Modelo.Conexion;
import java.awt.Dimension;
import java.awt.Graphics;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author HECTOR
 */
public class Modificar extends javax.swing.JPanel {
 Opciones Opciones;
 Veterinaria Veterinaria;
    
    /**
     * Creates new form Opciones
     */
    public Modificar() {
        initComponents();
        this.setBounds(0,0,800,510);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Regresar = new javax.swing.JButton();
        Modificar = new javax.swing.JButton();
        Nombre = new javax.swing.JTextField();
        Descuento = new javax.swing.JTextField();
        Apellidos = new javax.swing.JTextField();
        Direccion = new javax.swing.JTextField();
        Telefono = new javax.swing.JTextField();
        Correo = new javax.swing.JTextField();
        Buscar = new javax.swing.JButton();
        ID = new javax.swing.JTextField();

        Regresar.setOpaque(false);
        Regresar.setBorderPainted(false);
        Regresar.setContentAreaFilled(false);
        Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarActionPerformed(evt);
            }
        });

        Modificar.setOpaque(false);
        Modificar.setBorderPainted(false);
        Modificar.setContentAreaFilled(false);
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });

        Nombre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Nombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Nombre.setOpaque(false);
        Nombre.setBorder(null);

        Descuento.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Descuento.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Descuento.setOpaque(false);
        Descuento.setBorder(null);

        Apellidos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Apellidos.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Apellidos.setOpaque(false);
        Apellidos.setBorder(null);

        Direccion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Direccion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Direccion.setOpaque(false);
        Direccion.setBorder(null);

        Telefono.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Telefono.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Telefono.setOpaque(false);
        Telefono.setBorder(null);

        Correo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Correo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Correo.setOpaque(false);
        Correo.setBorder(null);

        Buscar.setOpaque(false);
        Buscar.setBorderPainted(false);
        Buscar.setContentAreaFilled(false);
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });

        ID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ID.setOpaque(false);
        ID.setBorder(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(Regresar, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(Modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                            .addComponent(Telefono))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Correo, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                            .addComponent(Descuento))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(218, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Correo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Descuento, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Modificar, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                    .addComponent(Regresar, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                    .addComponent(Buscar, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                    .addComponent(ID))
                .addGap(45, 45, 45))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed
     
    PreparedStatement ps;
    ResultSet rs;
    Conexion Con=new Conexion();
    Connection Conexion=Con.getconnection();
    
    try{
    ps=Conexion.prepareStatement("update cliente set Nombre=?,Apellidos=?,Direccion=?,Telefono=?,Correo_Electronico=?,Descuento=? where IdCliente=?");
    ps.setString(1,Nombre.getText());
     ps.setString(2,Apellidos.getText());
    ps.setString(3,Direccion.getText());
    ps.setString(4,Telefono.getText());
    ps.setString(5,Correo.getText());
    ps.setDouble(6,Double.valueOf(Descuento.getText()));
    ps.setInt(7, Integer.valueOf(ID.getText()));
    int Resultado=ps.executeUpdate();
    
    if(Resultado>0){
        JOptionPane.showMessageDialog(this,"Registro Modificado");
  
    }

    
    }catch(Exception e){
        System.out.println("Error: "+e);
      
    }
    finally{
    
    try{
    Conexion.close();
    }catch(Exception e){
        System.out.println("Error: "+e);
    }
    }
    
    
    
    }//GEN-LAST:event_ModificarActionPerformed
public void ant(Opciones Opciones, Veterinaria Veterinaria){

   this.Opciones=Opciones;
   this.Veterinaria=Veterinaria;
}
    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
      PreparedStatement ps;
    ResultSet rs;
        Conexion Con=new Conexion();
        Connection Conexion=Con.getconnection();
    
    try{
    ps=Conexion.prepareStatement("select * from cliente where IdCliente=?");
 ps.setString(1,ID.getText());
 
 rs=ps.executeQuery();
 
 if(rs.next()){
     Nombre.setText(rs.getString("Nombre"));
     Apellidos.setText(rs.getString("Apellidos"));
    Direccion.setText(rs.getString("Direccion"));
    Telefono.setText(rs.getString("Telefono"));
    Correo.setText(rs.getString("Correo_Electronico"));
   Descuento.setText(String.valueOf(rs.getDouble("Descuento")));
     


 }
 else{


 }
    
    }catch(Exception e){
        System.out.println("Error: "+e);
  
    }
    finally{
    
    try{
    Conexion.close();
    }catch(Exception e){
        System.out.println("Error: "+e);
    }
    }
    }//GEN-LAST:event_BuscarActionPerformed

    private void RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarActionPerformed
            this.setVisible(false);
            Veterinaria.add(Opciones);
             Opciones.setVisible(true);
    }//GEN-LAST:event_RegresarActionPerformed
  @Override
    public void paintComponent(Graphics g)
    {
        Dimension Tam=getSize();
        ImageIcon Imagen=new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/Modificar.jpg")).getImage());
        g.drawImage(Imagen.getImage(),0,0,Tam.width,Tam.height,null);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField Apellidos;
    public javax.swing.JButton Buscar;
    public javax.swing.JTextField Correo;
    public javax.swing.JTextField Descuento;
    public javax.swing.JTextField Direccion;
    public javax.swing.JTextField ID;
    public javax.swing.JButton Modificar;
    public javax.swing.JTextField Nombre;
    public javax.swing.JButton Regresar;
    public javax.swing.JTextField Telefono;
    // End of variables declaration//GEN-END:variables
}
