/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.Dimension;
import java.awt.Graphics;
import javax.swing.ImageIcon;

/**
 *
 * @author HECTOR
 */
public class RegistroMedico extends javax.swing.JPanel {

    /**
     * Creates new form RegistarEnfermera
     */
    public RegistroMedico() {
        initComponents();
          this.setBounds(0,0,800,510);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Nombre = new javax.swing.JTextField();
        Turno = new javax.swing.JTextField();
        Apellidos = new javax.swing.JTextField();
        Telefono = new javax.swing.JTextField();
        Correo = new javax.swing.JTextField();
        Direccion = new javax.swing.JTextField();
        Salario = new javax.swing.JTextField();
        Cedula = new javax.swing.JTextField();
        Regresar = new javax.swing.JButton();
        Insertar = new javax.swing.JButton();

        Nombre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Nombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Nombre.setOpaque(false);
        Nombre.setBorder(null);

        Turno.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Turno.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Turno.setOpaque(false);
        Turno.setBorder(null);

        Apellidos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Apellidos.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Apellidos.setOpaque(false);
        Apellidos.setBorder(null);

        Telefono.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Telefono.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Telefono.setOpaque(false);
        Telefono.setBorder(null);

        Correo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Correo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Correo.setOpaque(false);
        Correo.setBorder(null);

        Direccion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Direccion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Direccion.setOpaque(false);
        Direccion.setBorder(null);

        Salario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Salario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Salario.setOpaque(false);
        Salario.setBorder(null);

        Cedula.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Cedula.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Cedula.setOpaque(false);
        Cedula.setBorder(null);

        Regresar.setOpaque(false);
        Regresar.setBorderPainted(false);
        Regresar.setContentAreaFilled(false);

        Insertar.setOpaque(false);
        Insertar.setBorderPainted(false);
        Insertar.setContentAreaFilled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                    .addComponent(Telefono))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Direccion, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                    .addComponent(Apellidos))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Correo)
                    .addComponent(Salario))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Cedula, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(Turno))
                .addGap(78, 78, 78))
            .addGroup(layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(Regresar, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(129, 129, 129)
                .addComponent(Insertar, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(160, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(216, 216, 216)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Turno, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Correo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Salario, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cedula, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Regresar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Insertar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );
    }// </editor-fold>//GEN-END:initComponents

       @Override
    public void paintComponent(Graphics g)
    {
        Dimension Tam=getSize();
        ImageIcon Imagen=new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/Medicos.jpg")).getImage());
        g.drawImage(Imagen.getImage(),0,0,Tam.width,Tam.height,null);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField Apellidos;
    public javax.swing.JTextField Cedula;
    public javax.swing.JTextField Correo;
    public javax.swing.JTextField Direccion;
    public javax.swing.JButton Insertar;
    public javax.swing.JTextField Nombre;
    public javax.swing.JButton Regresar;
    public javax.swing.JTextField Salario;
    public javax.swing.JTextField Telefono;
    public javax.swing.JTextField Turno;
    // End of variables declaration//GEN-END:variables
}
